version: "3.7"

services:
  ontologysim_api:
    container_name: onto_be
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - "5000:5000"

  frontend:
    container_name: onto_fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
